/* Generated by tools/extractVis1.mjs from widgets/metro.html - do not edit. */

export interface Vis1Template {
    /** data-vis-name */
    name: string;
    /** data-vis-type */
    type: string;
    /** data-vis-attrs*, concatenated - the attribute DSL of vis-1, see src/visAttrs.ts */
    attrs: string;
}

export const VIS1: Record<string, Vis1Template> = {
    tplMetroSlider: {
        name: 'Slider horizontal',
        type: 'ctrl,slider,dimmer',
        attrs: 'oid;oid-working;min;max;step;sliderColor/color;sliderCompleteColor/color;sliderMarkerColor/color',
    },
    tplMetroSliderVertical: {
        name: 'Slider vertical',
        type: 'ctrl,slider,dimmer',
        attrs: 'oid;oid-working;min;max;step;sliderColor/color;sliderCompleteColor/color;sliderMarkerColor/color',
    },
    tplMetroValueBoolCheckbox: {
        name: 'Bool Checkbox',
        type: 'ctrl,bool',
        attrs: 'html_prepend;html_append;oid',
    },
    tplMetroValueBoolSwitch: {
        name: 'Switch',
        type: 'ctrl,bool',
        attrs: 'html_prepend;html_append;oid',
    },
    tplMetroTileNav: {
        name: 'Tile Navigation',
        type: 'static,navigation',
        attrs: 'nav_view;hover[true]/checkbox;transform[true]/checkbox;select_current/checkbox;label[Navigation];bg_class[bg-indigo]/style,metro-,bg- ribbed-;bg_class_active[bg-magenta]/style,metro-,bg- ribbed-;group.badge;badge_bg_class[bg-cyan]/style,metro-,bg-;badge_bg_class_active[bg-teal]/style,metro-,bg-;badge_src/image;badge_width/slider,0,100,1;badge_height/slider,0,100,1;badge_top[0]/slider,0,100,1;badge_left[0]/slider,0,100,1;icon_badge[icon-file]/style,iconFont,icon-,,Icon ;brand_bg_class[ribbed-steel]/style,metro-,bg- ribbed-;brand_bg_class_active[ribbed-indigo]/style,metro-,bg- ribbed-;group.icon;icon_src/image;icon_width/slider,0,100,1;icon_height/slider,0,100,1;icon_top/slider,0,100,1;icon_left/slider,0,100,1;icon_class[icon-new]/style,iconFont,icon-,,Icon ;group.effects;sync/checkbox;hide_effect/effect;hide_duration/slider,0,10000,100;hide_options/effect-options;show_effect/effect;show_duration/slider,0,10000,100;show_options/effect-options;body-background/color',
    },
    tplMetroTileString: {
        name: 'Tile String',
        type: 'val',
        attrs: 'content_prepend;content_append;content_oid/id;state_oid/id;hover/checkbox;transform/checkbox;select_on_true/checkbox;bg_class_false[bg-indigo]/style,metro-,bg- ribbed-;bg_class_true[bg-teal]/style,metro-,bg- ribbed-;group.icon;icon_false/image;icon_true/image;icon_width/slider,0,100,1;icon_height/slider,0,100,1;icon_top/slider,0,100,1;icon_left/slider,0,100,1;icon_class_false[icon-sun-3]/style,iconFont,icon-,,Icon ;icon_class_true[icon-weather-4]/style,iconFont,icon-,,Icon ;group.badge;label_prepend;label_append;label_id/id;badge_bg_class_false[bg-cyan]/style,metro-,bg-;badge_bg_class_true[bg-teal]/style,metro-,bg-;icon_badge_false[icon-sunrise]/style,iconFont,icon-,,Icon ;icon_badge_true[icon-sunrise]/style,iconFont,icon-,,Icon ;brand_bg_class_false[ribbed-steel]/style,metro-,bg- ribbed-;brand_bg_class_true[ribbed-indigo]/style,metro-,bg- ribbed-;badge_src_false/image;badge_src_true/image;badge_width/slider,0,100,1;badge_height/slider,0,100,1;badge_top[0]/slider,0,100,1;badge_left[0]/slider,0,100,1;',
    },
    tplMetroTileBool: {
        name: 'Tile Bool',
        type: 'val,bool',
        attrs: 'oid;hover[true]/checkbox;transform/checkbox;select_on_true/checkbox;label_false[false];label_true[true];bg_class_false[bg-indigo]/style,metro-,bg- ribbed-;bg_class_true[bg-teal]/style,metro-,bg- ribbed-;group.icon;icon_false/image;icon_true/image;icon_width/slider,0,100,1;icon_height/slider,0,100,1;icon_top/slider,0,100,1;icon_left/slider,0,100,1;icon_class_false[icon-cancel-2]/style,iconFont,icon-,,Icon ;icon_class_true[icon-checkmark]/style,iconFont,icon-,,Icon ;group.badge;icon_badge_false[icon-folder-2]/style,iconFont,icon-,,Icon ;icon_badge_true[icon-folder]/style,iconFont,icon-,,Icon ;badge_bg_class_false[bg-cyan]/style,metro-,bg-;badge_bg_class_true[bg-teal]/style,metro-,bg-;badge_src_false/image;badge_src_true/image;badge_width/slider,0,100,1;badge_height/slider,0,100,1;badge_top[0]/slider,0,100,1;badge_left[0]/slider,0,100,1;brand_bg_class_false[ribbed-steel]/style,metro-,bg- ribbed-;brand_bg_class_true[ribbed-indigo]/style,metro-,bg- ribbed-;',
    },
    tplMetroTileBoolDialog: {
        name: 'Tile Bool Dialog',
        type: 'bool,dialog',
        attrs: 'oid;hover[true]/checkbox;transform/checkbox;select_on_true/checkbox;label_false[false];label_true[true];bg_class_false[bg-indigo]/style,metro-,bg- ribbed-;bg_class_true[bg-teal]/style,metro-,bg- ribbed-;group.icon;icon_false/image;icon_true/image;icon_width/slider,0,100,1;icon_height/slider,0,100,1;icon_top/slider,0,100,1;icon_left/slider,0,100,1;icon_class_false[icon-cancel-2]/style,iconFont,icon-,,Icon ;icon_class_true[icon-checkmark]/style,iconFont,icon-,,Icon ;group.badge;icon_badge_false[icon-folder-2]/style,iconFont,icon-,,Icon ;icon_badge_true[icon-folder]/style,iconFont,icon-,,Icon ;badge_bg_class_false[bg-cyan]/style,metro-,bg-;badge_bg_class_true[bg-teal]/style,metro-,bg-;badge_src_false/image;badge_src_true/image;badge_width/slider,0,100,1;badge_height/slider,0,100,1;badge_top[0]/slider,0,100,1;badge_left[0]/slider,0,100,1;brand_bg_class_false[ribbed-steel]/style,metro-,bg- ribbed-;brand_bg_class_true[ribbed-indigo]/style,metro-,bg- ribbed-;group.dialog;contains_view/views;dialog_width;dialog_height;dialog_title;dialog_flat/checkbox;dialog_shadow/checkbox;dialog_draggable[true]/checkbox;dialog_modal/checkbox;dialog_icon_src/image;dialog_icon_class[]/style,iconFont,icon-,,Icon ;',
    },
    tplMetroTileList8: {
        name: 'Tile ValueList 8',
        type: 'val,list',
        attrs: 'oid;hover/checkbox;transform/checkbox;label_prepend;label_append;group.bg-and-text;label(0-7)[Value list];bg_class(0-7)[bg-indigo]/style,metro-,bg- ribbed-;group.icon;icon(0-7)/image;icon_width/slider,0,100,1;icon_height/slider,0,100,1;icon_top/slider,0,100,1;icon_left/slider,0,100,1;icon_class(0-7)[icon-pencil]/style,iconFont,icon-,,Icon ;group.badge;icon_badge(0-7)[icon-pencil]/style,iconFont,icon-,,Icon ;badge_bg_class(0-7)[bg-cyan]/style,metro-,bg-;brand_bg_class(0-7)[ribbed-steel]/style,metro-,bg- ribbed-;badge_src/image;badge_width/slider,0,100,1;badge_height/slider,0,100,1;badge_top[0]/slider,0,100,1;badge_left[0]/slider,0,100,1;',
    },
    tplMetroTileBoolNumber: {
        name: 'Tile Bool / Number',
        type: 'val,bool',
        attrs: 'state_oid/id;select_on_true/checkbox;number_oid/id;hover[true]/checkbox;transform/checkbox;label_false;label_true;label_append;bg_class_false[bg-indigo]/style,metro-,bg- ribbed-;bg_class_true[bg-teal]/style,metro-,bg- ribbed-;group.icon;icon_false_src/image;icon_true_src/image;icon_width/slider,0,100,1;icon_height/slider,0,100,1;icon_top/slider,0,100,1;icon_left/slider,0,100,1;icon_class_false[icon-cancel-2]/style,iconFont,icon-,,Icon ;icon_class_true[icon-checkmark]/style,iconFont,icon-,,Icon ;group.badge;icon_badge_false[]/style,iconFont,icon-,,Icon ;icon_badge_true[]/style,iconFont,icon-,,Icon ;badge_bg_class_false[bg-cyan]/style,metro-,bg-;badge_bg_class_true[bg-teal]/style,metro-,bg-;brand_bg_class_false[ribbed-steel]/style,metro-,bg- ribbed-;brand_bg_class_true[ribbed-indigo]/style,metro-,bg- ribbed-;badge_src_false/image;badge_src_true/image;badge_width/slider,0,100,1;badge_height/slider,0,100,1;badge_top[0]/slider,0,100,1;badge_left[0]/slider,0,100,1;',
    },
    tplMetroTileState: {
        name: 'Tile State',
        type: 'ctrl',
        attrs: 'state_oid/id;value;select_on_value/checkbox;hover[true]/checkbox;transform[true]/checkbox;label_false;label_true;bg_class_false[bg-indigo]/style,metro-,bg- ribbed-;bg_class_true[bg-teal]/style,metro-,bg- ribbed-;group.icon;icon_false/image;icon_true/image;icon_width/slider,0,100,1;icon_height/slider,0,100,1;icon_top/slider,0,100,1;icon_left/slider,0,100,1;icon_class_false[]/style,iconFont,icon-,,Icon ;icon_class_true[]/style,iconFont,icon-,,Icon ;group.badge;icon_badge_false[]/style,iconFont,icon-,,Icon ;icon_badge_true[]/style,iconFont,icon-,,Icon ;badge_bg_class_false[bg-cyan]/style,metro-,bg-;badge_bg_class_true[bg-teal]/style,metro-,bg-;brand_bg_class_false[ribbed-steel]/style,metro-,bg- ribbed-;brand_bg_class_true[ribbed-indigo]/style,metro-,bg- ribbed-;badge_src_false/image;badge_src_true/image;badge_width/slider,0,100,1;badge_height/slider,0,100,1;badge_top[0]/slider,0,100,1;badge_left[0]/slider,0,100,1;',
    },
    tplMetroTileToggle: {
        name: 'Tile Toggle',
        type: 'ctrl,bool',
        attrs: 'oid;hover[true]/checkbox;transform[true]/checkbox;select_on_true/checkbox;label_false;label_true;bg_class_false[bg-indigo]/style,metro-,bg- ribbed-;bg_class_true[bg-teal]/style,metro-,bg- ribbed-;group.icon;icon_false/image;icon_true/image;icon_width/slider,0,100,1;icon_height/slider,0,100,1;icon_top/slider,0,100,1;icon_left/slider,0,100,1;icon_class_false[icon-minus]/style,iconFont,icon-,,Icon ;icon_class_true[icon-plus]/style,iconFont,icon-,,Icon ;group.badge;icon_badge_false[icon-minus-2]/style,iconFont,icon-,,Icon ;icon_badge_true[icon-plus-2]/style,iconFont,icon-,,Icon ;badge_bg_class_false[bg-cyan]/style,metro-,bg-;badge_bg_class_true[bg-teal]/style,metro-,bg-;brand_bg_class_false[ribbed-steel]/style,metro-,bg- ribbed-;brand_bg_class_true[ribbed-indigo]/style,metro-,bg- ribbed-;badge_src_false/image;badge_src_true/image;badge_width/slider,0,100,1;badge_height/slider,0,100,1;badge_top[0]/slider,0,100,1;badge_left[0]/slider,0,100,1;group.ccontrol;urlTrue;urlFalse;oidTrue/id;oidFalse/id;oidTrueValue;oidFalseValue;',
    },
    tplMetroTileStateNumber: {
        name: 'Tile State / val Badge Number',
        type: 'val',
        attrs: 'state_oid/id;value;select_on_value/checkbox;number_oid/id;hover[true]/checkbox;transform[true]/checkbox;label_false;label_true;label_append;bg_class_false[bg-indigo]/style,metro-,bg- ribbed-;bg_class_true[bg-teal]/style,metro-,bg- ribbed-;group.icon;icon_false_src/image;icon_true_src/image;icon_width/slider,0,100,1;icon_height/slider,0,100,1;icon_top/slider,0,100,1;icon_left/slider,0,100,1;icon_class_false[icon-meter-slow]/style,iconFont,icon-,,Icon ;icon_class_true[icon-meter-fast]/style,iconFont,icon-,,Icon ;group.badge;badge_bg_class[]/style,metro-,bg-;hide_on_0/checkbox;group.brand;brand_bg_class_false[ribbed-steel]/style,metro-,bg- ribbed-;brand_bg_class_true[ribbed-indigo]/style,metro-,bg- ribbed-;',
    },
    tplMetroTileDimmer: {
        name: 'Tile Dimmer',
        type: 'ctrl,dimmer',
        attrs: 'oid;oid-working;min;max;step[1];hover/checkbox;transform/checkbox;label;bg_class[bg-indigo]/style,metro-,bg- ribbed-;brand_bg_class[ribbed-steel]/style,metro-,bg- ribbed-;group.slider;sliderColor/color;sliderCompleteColor/color;sliderMarkerColor/color',
    },
    tplMetroTileDimmerDialog: {
        name: 'Tile Dimmer Dialog',
        type: 'ctrl,dimmer,dialog',
        attrs: 'oid;oid-working;min;max;step[1];digits/number;hover[true]/checkbox;transform[true]/checkbox;label;bg_class[bg-indigo]/style,metro-,bg- ribbed-;brand_bg_class[ribbed-steel]/style,metro-,bg- ribbed-;group.slider;sliderColor/color;sliderCompleteColor/color;sliderMarkerColor/color;group.dialog;dialog_flat/checkbox;dialog_shadow/checkbox;dialog_draggable[true]/checkbox;dialog_modal/checkbox',
    },
    tplMetroTileShutter: {
        name: 'Tile Shutter',
        type: 'ctrl,shutter',
        attrs: 'oid;oid-working;min;max;step[1];hover/checkbox;transform/checkbox;label;bg_class[bg-indigo]/style,metro-,bg- ribbed-;brand_bg_class[ribbed-steel]/style,metro-,bg- ribbed-;group.slider;sliderColor/color;sliderCompleteColor/color;sliderMarkerColor/color',
    },
    tplMetroTileShutterDialog: {
        name: 'Tile Shutter Dialog',
        type: 'ctrl,shutter,dialog',
        attrs: 'oid;oid-working;min;max;step[1];hover[true]/checkbox;transform[true]/checkbox;label;bg_class[bg-indigo]/style,metro-,bg- ribbed-;brand_bg_class[ribbed-steel]/style,metro-,bg- ribbed-;group.slider;sliderColor/color;sliderCompleteColor/color;sliderMarkerColor/color;group.dialog;dialog_flat/checkbox;dialog_shadow/checkbox;dialog_draggable[true]/checkbox;dialog_modal/checkbox',
    },
    tplMetroTileHeating: {
        name: 'Tile Heating',
        type: 'ctrl,heating',
        attrs: 'set_oid/id/onHeatingOid;temp_oid/id;drive_oid/id;hum_oid/id;hover/checkbox;transform/checkbox;label;min[6]/slider,-20,40,1;max[30]/slider,-20,40,1;step;bg_class[bg-indigo]/style,metro-,bg- ribbed-;brand_bg_class[ribbed-steel]/style,metro-,bg- ribbed-;label_set;label_temp;label_drive;label_humidity;group.slider;sliderColor/color;sliderCompleteColor/color;sliderMarkerColor/color;group.service;lowbat_oid/id;icon_lowbat[icon-battery]/style,iconFont,icon-,,Icon;controlmode_oid/id;icon_control_mode_0[icon-clock]/style,iconFont,icon-,,Icon;icon_control_mode_1[icon-radio-unchecked]/style,iconFont,icon-,,Icon;icon_control_mode_2[icon-briefcase]/style,iconFont,icon-,,Icon;windowopen_oid/id;icon_windowopen[icon-enter]/style,iconFont,icon-,,Icon;badge_bg_class[]/style,metro-,bg-;',
    },
    tplMetroTileHeatingDialog: {
        name: 'Tile Heating Dialog',
        type: 'ctrl,heating,dialog',
        attrs: 'set_oid/id/onHeatingOid;temp_oid/id;drive_oid/id;hover[true]/checkbox;transform[true]/checkbox;label;min[6]/slider,-20,40,1;max[30]/slider,-20,40,1;step;bg_class[bg-indigo]/style,metro-,bg- ribbed-;brand_bg_class[ribbed-steel]/style,metro-,bg- ribbed-;label_short_set;label_short_temp;label_short_drive;label_set;label_temp;label_drive;group.slider;sliderColor/color;sliderCompleteColor/color;sliderMarkerColor/color;group.dialog;dialog_flat/checkbox;dialog_shadow/checkbox;dialog_draggable[true]/checkbox;dialog_modal/checkbox',
    },
    tplMetroTileDialogStatic: {
        name: 'static - Tile Dialog',
        type: 'ctrl,dialog',
        attrs: 'label;content_oid/id;hover[true]/checkbox;transform[true]/checkbox;bg_class[bg-indigo]/style,metro-,bg- ribbed-;group.icon;icon_src/image;icon_width/slider,0,100,1;icon_height/slider,0,100,1;icon_top/slider,0,100,1;icon_left/slider,0,100,1;icon_class[]/style,iconFont,icon-,,Icon ;group.badge;icon_badge[]/style,iconFont,icon-,,Icon ;badge_bg_class[]/style,metro-,bg-;brand_bg_class[ribbed-steel]/style,metro-,bg- ribbed-;group.dialog;html/html;dialog_width;dialog_height;dialog_title;dialog_flat/checkbox;dialog_shadow/checkbox;dialog_draggable[true]/checkbox;dialog_modal/checkbox;dialog_icon_src/image;dialog_icon_class[]/style,iconFont,icon-,,Icon ;',
    },
    tplMetroTileStaticDialogNumber: {
        name: 'Tile Dialog / val - Badge Number',
        type: 'static,dialog',
        attrs: 'content_oid/id;number_oid/id;hide_on_0/checkbox;hover[true]/checkbox;transform[true]/checkbox;bg_class[bg-indigo]/style,metro-,bg- ribbed-;group.icon;icon_src/image;icon_width/slider,0,100,1;icon_height/slider,0,100,1;icon_top/slider,0,100,1;icon_left/slider,0,100,1;icon_class[icon-pictures]/style,iconFont,icon-,,Icon ;group.badge;label;badge_bg_class[]/style,metro-,bg-;brand_bg_class[ribbed-steel]/style,metro-,bg- ribbed-;group.dialog;html/html;dialog_width;dialog_height;dialog_title;dialog_flat/checkbox;dialog_shadow/checkbox;dialog_draggable[true]/checkbox;dialog_modal/checkbox;dialog_icon_src/image;dialog_icon_class[]/style,iconFont,icon-,,Icon ;',
    },
    tplMetroTileDialogString: {
        name: 'Tile Dialog',
        type: 'val,dialog',
        attrs: 'content_oid/id;dialog_oid/id;hover[true]/checkbox;transform[true]/checkbox;bg_class[bg-indigo]/style,metro-,bg- ribbed-;group.icon;icon_src/image;icon_width/slider,0,100,1;icon_height/slider,0,100,1;icon_top/slider,0,100,1;icon_left/slider,0,100,1;icon_class[]/style,iconFont,icon-,,Icon ;group.badge;label;icon_badge[]/style,iconFont,icon-,,Icon ;badge_bg_class[]/style,metro-,bg-;brand_bg_class[ribbed-steel]/style,metro-,bg- ribbed-;group.dialog;dialog_fontSize[12px];dialog_padding[0px 0px 0px 0px];dialog_textAlign;dialog_width;dialog_height;dialog_title;dialog_flat/checkbox;dialog_shadow/checkbox;dialog_draggable[true]/checkbox;dialog_modal/checkbox;dialog_icon_src/image;dialog_icon_class[]/style,iconFont,icon-,,Icon ;',
    },
    tplMetroTileStringDialogNumber: {
        name: 'Tile Dialog / Badge Number',
        type: 'val,dialog',
        attrs: 'content_oid/id;dialog_oid/id;number_oid/id;hide_on_0/checkbox;hover[true]/checkbox;transform[true]/checkbox;bg_class[bg-indigo]/style,metro-,bg- ribbed-;group.icon;icon_src/image;icon_width/slider,0,100,1;icon_height/slider,0,100,1;icon_top/slider,0,100,1;icon_left/slider,0,100,1;icon_class[icon-database]/style,iconFont,icon-,,Icon ;group.badge;label;badge_bg_class[]/style,metro-,bg-;brand_bg_class[ribbed-steel]/style,metro-,bg- ribbed-;group.dialog;dialog_fontSize[12px];dialog_padding[0px 0px 0px 0px];dialog_textAlign;dialog_width;dialog_height;dialog_title;dialog_flat/checkbox;dialog_shadow/checkbox;dialog_draggable[true]/checkbox;dialog_modal/checkbox;dialog_icon_src/image;dialog_icon_class[]/style,iconFont,icon-,,Icon ;',
    },
    tplMetroTileDialog: {
        name: 'Tile Dialog',
        type: 'container,dialog',
        attrs: 'contains_view/views;hover[true]/checkbox;transform[true]/checkbox;bg_class[bg-indigo]/style,metro-,bg- ribbed-;group.icon;icon_src/image;icon_width/slider,0,100,1;icon_height/slider,0,100,1;icon_top/slider,0,100,1;icon_left/slider,0,100,1;icon_class[icon-pictures]/style,iconFont,icon-,,Icon ;group.badge;label;icon_badge[]/style,iconFont,icon-,,Icon ;badge_bg_class[]/style,metro-,bg-;brand_bg_class[ribbed-steel]/style,metro-,bg- ribbed-;group.dialog;dialog_width;dialog_height;dialog_title;dialog_flat/checkbox;dialog_shadow/checkbox;dialog_draggable[true]/checkbox;dialog_modal/checkbox;dialog_icon_src/image;dialog_icon_class[]/style,iconFont,icon-,,Icon ;',
    },
    tplMetroTileDialogNumber: {
        name: 'Tile Dialog / val - Badge Number',
        type: 'container,dialog',
        attrs: 'contains_view/views;number_oid/id;hide_on_0/checkbox;hover[true]/checkbox;transform[true]/checkbox;bg_class[]/style,metro-,bg- ribbed-;group.icon;icon_src/image;icon_width/slider,0,100,1;icon_height/slider,0,100,1;icon_top/slider,0,100,1;icon_left/slider,0,100,1;icon_class[]/style,iconFont,icon-,,Icon ;group.badge;label;badge_bg_class[]/style,metro-,bg-;brand_bg_class[ribbed-steel]/style,metro-,bg- ribbed-;group.dialog;dialog_width;dialog_height;dialog_title;dialog_flat/checkbox;dialog_shadow/checkbox;dialog_draggable[true]/checkbox;dialog_modal/checkbox;dialog_icon_src/image;dialog_icon_class[]/style,iconFont,icon-,,Icon ;',
    },
    tplMetroTileFrameDialogNumber: {
        name: 'Tile Dialog / iFrame',
        type: 'iframe,dialog',
        attrs: 'content;hover[true]/checkbox;transform[true]/checkbox;bg_class[bg-indigo]/style,metro-,bg- ribbed-;group.icon;icon_src/image;icon_width/slider,0,100,1;icon_height/slider,0,100,1;icon_top/slider,0,100,1;icon_left/slider,0,100,1;icon_class[icon-accessibility]/style,iconFont,icon-,,Icon ;group.badge;label;badge_label;badge_bg_class[]/style,metro-,bg-;brand_bg_class[ribbed-steel]/style,metro-,bg- ribbed-;group.dialog;dialog_url[https:~~maps.google.com~maps?f=q&source=s_q&hl=de&geocode=&q=Karlsruhe&ie=UTF8&t=m&z=12&output=embed&iwloc=near];dialog_scroll;dialog_width[400px];dialog_height[300px];dialog_title[Google maps];dialog_flat[true]/checkbox;dialog_shadow[true]/checkbox;dialog_draggable[true]/checkbox;dialog_modal/checkbox;dialog_icon_src/image;dialog_icon_class[icon-globe]/style,iconFont,icon-,,Icon ;',
    },
    tplMetroTileToggleNumber: {
        name: 'Tile Toggle - Bage Number',
        type: 'ctrl,bool',
        attrs: 'oid;number_oid/id;hide_on_0/checkbox;hover[true]/checkbox;transform[true]/checkbox;select_on_true/checkbox;label_false;label_true;bg_class_false[bg-indigo]/style,metro-,bg- ribbed-;bg_class_true[bg-teal]/style,metro-,bg- ribbed-;group.icon;icon_false/image;icon_true/image;icon_width/slider,0,100,1;icon_height/slider,0,100,1;icon_top/slider,0,100,1;icon_left/slider,0,100,1;icon_class_false[icon-minus]/style,iconFont,icon-,,Icon ;icon_class_true[icon-plus]/style,iconFont,icon-,,Icon ;group.badge;badge_bg_class[]/style,metro-,bg-;badge_bg_class_false[bg-cyan]/style,metro-,bg-;badge_bg_class_true[bg-teal]/style,metro-,bg-;brand_bg_class_false[ribbed-steel]/style,metro-,bg- ribbed-;brand_bg_class_true[ribbed-indigo]/style,metro-,bg- ribbed-;group.ccontrol;urlTrue;urlFalse;oidTrue/id;oidFalse/id;oidTrueValue;oidFalseValue;',
    },
    tplMetroTileDimmerDialogactiv: {
        name: 'Tile Dimmer Dialog activ',
        type: 'ctrl,dimmer,dialog',
        attrs: 'oid;oid-working;min;max;step[1];digits/number;hover[true]/checkbox;transform[true]/checkbox;label;bg_class[bg-indigo]/style,metro-,bg- ribbed-;brand_bg_class[ribbed-steel]/style,metro-,bg- ribbed-;brand_bg_class_false[ribbed-steel]/style,metro-,bg- ribbed-;brand_bg_class_true[ribbed-indigo]/style,metro-,bg- ribbed-;group.slider;sliderColor/color;sliderCompleteColor/color;sliderMarkerColor/color;group.dialog;dialog_flat/checkbox;dialog_shadow/checkbox;dialog_draggable[true]/checkbox;dialog_modal/checkbox;autoclose/slider,0,30000,100;',
    },
};
