/**
 * Builds src/styles/metro-iconFont.css and copies the two fonts the widgets need into public/fonts/.
 *
 *   node tools/extractIcons.mjs
 *
 * The 452 `icon-*` classes are the one part of the vis-1 set that cannot be rewritten: their names are stored in
 * the user's project and each one maps to a glyph of a font built with IcoMoon. So the stylesheet is taken over
 * as it is, with two changes:
 *
 *   - the scope goes from `.metro` to `.metro-rx`, otherwise the icons of a React widget stay invisible - the
 *     vis-1 `iconFont.min.css` only matches inside `.metro`;
 *   - `@font-face` loses the `eot` and `svg` sources, which existed for IE8 and old Android.
 *
 * It lands in `public/` instead of `src/`, so vite copies it verbatim and the NAME survives. That matters: both
 * dropdowns of the editor filter the collected classes by the file name of the stylesheet they came from
 * (`filterFile`, see src/fields.ts), and `metro-iconFont.css` satisfies the `iconFont` filter of the icon
 * dropdown and the `metro-` filter of the colour dropdown at once. A stylesheet imported from a .tsx would be
 * bundled into `assets/metro-<chunk>-<hash>.css` instead and lose the `iconFont` part of its name.
 *
 * `Generic` links it into the page, see `Generic.linkIconFont()`.
 */
import { copyFileSync, mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const LEGACY = join(ROOT, '../widgets/metro');
const TARGET = join(ROOT, 'public/styles/metro-iconFont.css');
const FONT_DIR = join(ROOT, 'public/fonts');

/** woff first, ttf as the fallback - everything else was for browsers that cannot run vis-2 anyway. */
const FONTS = ['iconFont.woff', 'iconFont.ttf', 'metroSysIcons.woff', 'metroSysIcons.ttf'];

const fontFace = (family, base) =>
    `@font-face {\n` +
    `    font-family: '${family}';\n` +
    `    src:\n` +
    `        url('../fonts/${base}.woff') format('woff'),\n` +
    `        url('../fonts/${base}.ttf') format('truetype');\n` +
    `    font-weight: normal;\n` +
    `    font-style: normal;\n` +
    `    font-display: block;\n}`;

const icons = readFileSync(join(LEGACY, 'css/iconFont.min.css'), 'utf8')
    // drop the original @font-face, it is rebuilt above
    .replace(/@font-face\s*\{[^}]*\}/g, '')
    .replace(/\.metro(?![\w-])/g, '.metro-rx')
    .trim();

// `.tile.selected` and the checkbox draw their check mark from this second, much smaller font.
const sysIcons = readFileSync(join(LEGACY, 'css/metro-bootstrap.css'), 'utf8').includes('metroSysIcons');
if (!sysIcons) {
    throw new Error('metroSysIcons font-face not found in metro-bootstrap.css');
}

const out =
    `/* Generated by tools/extractIcons.mjs from widgets/metro/css/iconFont.min.css - do not edit. */\n\n` +
    `${fontFace('iconFont', 'iconFont')}\n\n${fontFace('metroSysIcons', 'metroSysIcons')}\n\n${icons}\n`;

mkdirSync(dirname(TARGET), { recursive: true });
writeFileSync(TARGET, out);

mkdirSync(FONT_DIR, { recursive: true });
let bytes = 0;
for (const font of FONTS) {
    const from = join(LEGACY, 'fonts', font);
    copyFileSync(from, join(FONT_DIR, font));
    bytes += statSync(from).size;
}

const classes = new Set(out.match(/\.icon-[a-zA-Z0-9_-]+/g) || []);
console.log(`public/styles/metro-iconFont.css: ${(out.length / 1024).toFixed(1)} KB, ${classes.size} icon classes`);
console.log(`public/fonts: ${FONTS.join(', ')} (${(bytes / 1024).toFixed(0)} KB)`);
