/**
 * Takes over what the React widgets must not get wrong from the vis-1 widget set, widgets/metro.html:
 *
 *   - src/vis1.generated.ts   the attribute list of every template (`data-vis-attrs*`) verbatim, plus its name
 *                             and type - the React widgets build their editor fields from it (src/visAttrs.ts), so
 *                             the names, defaults, types, order and groups are the ones stored in the projects
 *   - src/i18n/*.json         the labels: the `systemDictionary` of metro.html (en, de, ru), overridden and
 *                             completed by tools/i18n-extra.json; languages without a translation get English
 *
 *   node tools/extractVis1.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const LEGACY = join(ROOT, '../widgets/metro.html');
const html = readFileSync(LEGACY, 'utf8');

/** The start tag holds HTML in `data-vis-prev`, so its attributes are tokenised instead of matched with a regex */
function parseTemplates() {
    const templates = [];
    let pos = 0;
    while ((pos = html.indexOf('<script id="tpl', pos)) !== -1) {
        let i = pos + '<script'.length;
        const attrs = {};
        for (;;) {
            while (/\s/.test(html[i])) {
                i++;
            }
            if (html[i] === '>') {
                i++;
                break;
            }
            const named = /^([\w-]+)\s*=\s*(["'])/.exec(html.slice(i, i + 200));
            if (!named) {
                const flag = /^[\w-]+/.exec(html.slice(i))[0];
                attrs[flag] = true;
                i += flag.length;
                continue;
            }
            const end = html.indexOf(named[2], i + named[0].length);
            attrs[named[1]] = html.slice(i + named[0].length, end);
            i = end + 1;
        }
        pos = html.indexOf('</script>', i);
        // data-vis-attrs, data-vis-attrs0 ... data-vis-attrs10 - in that order, as vis concatenates them
        const parts = Object.keys(attrs)
            .filter(key => /^data-vis-attrs\d*$/.test(key))
            .sort((a, b) => (parseInt(a.slice(14), 10) || -1) - (parseInt(b.slice(14), 10) || -1))
            .map(key => attrs[key]);
        templates.push({ id: attrs.id, name: attrs['data-vis-name'], type: attrs['data-vis-type'], attrs: parts.join('') });
    }
    return templates;
}

/** The `$.extend(true, systemDictionary, {...})` blocks of metro.html */
function parseDictionary() {
    const words = {};
    const re = /\$\.extend\(\s*true\s*,\s*systemDictionary\s*,\s*\{/g;
    let m;
    while ((m = re.exec(html))) {
        let depth = 1;
        let i = m.index + m[0].length;
        for (; i < html.length && depth; i++) {
            if (html[i] === '{') {
                depth++;
            } else if (html[i] === '}') {
                depth--;
            }
        }
        // our own file: an object literal of strings
        Object.assign(words, new Function(`return {${html.slice(m.index + m[0].length, i - 1)}}`)());
    }
    return words;
}

const templates = parseTemplates();
const quote = s => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
const ts =
    `/* Generated by tools/extractVis1.mjs from widgets/metro.html - do not edit. */\n\n` +
    `export interface Vis1Template {\n    /** data-vis-name */\n    name: string;\n    /** data-vis-type */\n    type: string;\n` +
    `    /** data-vis-attrs*, concatenated - the attribute DSL of vis-1, see src/visAttrs.ts */\n    attrs: string;\n}\n\n` +
    `export const VIS1: Record<string, Vis1Template> = {\n${templates
        .map(t => `    ${t.id}: {\n        name: ${quote(t.name)},\n        type: ${quote(t.type)},\n        attrs: ${quote(t.attrs)},\n    },`)
        .join('\n')}\n};\n`;
writeFileSync(join(ROOT, 'src/vis1.generated.ts'), ts);

const LANGUAGES = ['en', 'de', 'ru', 'pt', 'nl', 'fr', 'it', 'es', 'pl', 'uk', 'zh-cn'];
const dictionary = parseDictionary();
const extra = JSON.parse(readFileSync(join(ROOT, 'tools/i18n-extra.json'), 'utf8'));
const merged = { ...dictionary, ...extra };

// `label(0-7)` becomes the fields label0 ... label7, and vis-2 translates a field label as it is - so every one of
// them gets its own key: "Label [3]"
for (const template of templates) {
    for (const m of template.attrs.matchAll(/(?:^|;)([^;[(/]+)\((\d+)-(\d+)\)/g)) {
        const [, base, from, to] = m;
        for (let i = parseInt(from, 10); i <= parseInt(to, 10); i++) {
            const texts = merged[base] || { en: base };
            merged[`${base}${i}`] = Object.fromEntries(
                Object.entries(texts).map(([lang, text]) => [lang, `${text} [${i}]`]),
            );
        }
    }
}
for (const lang of LANGUAGES) {
    const out = {};
    for (const key of Object.keys(merged).sort()) {
        out[key] = merged[key][lang] || merged[key].en || key;
    }
    writeFileSync(join(ROOT, `src/i18n/${lang}.json`), `${JSON.stringify(out, null, 4)}\n`);
}

console.log(`src/vis1.generated.ts: ${templates.length} templates`);
console.log(`src/i18n: ${Object.keys(merged).length} keys (${Object.keys(dictionary).length} from metro.html, ${Object.keys(extra).length} from i18n-extra.json)`);
