/**
 * Generates src/styles/metro-palette.css from tools/palette.mjs.
 *
 *   node tools/generate.mjs           write the stylesheet
 *   node tools/generate.mjs --verify  compare it against widgets/metro/css/metro-bootstrap.css
 *
 * --verify is the safety net for the migration: it proves that the generated classes carry the same
 * values as the original ones and lists every colour class the original had that we no longer emit.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { COLORS, RIBBED, RIBBED_OVERRIDES, RIBBED_GRADIENT, STATES } from './palette.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const TARGET = join(ROOT, 'src/styles/metro-palette.css');
const ORIGINAL = join(ROOT, '../widgets/metro/css/metro-bootstrap.css');

/** The class names of the vis-1 set are kept; only the ancestor scope changes, so the two stylesheets
 *  can live in the same document without fighting over specificity. */
const SCOPE = '.metro-rx';

const ribbedColor = name => RIBBED_OVERRIDES[name] || COLORS[name];

function buildPaletteCss() {
    const head = `/* Generated by tools/generate.mjs - do not edit, change tools/palette.mjs instead. */\n`;
    const bg = Object.entries(COLORS)
        .map(([name, value]) => `${SCOPE} .bg-${name} { background-color: ${value} !important; }`)
        .join('\n');
    const fg = Object.entries(COLORS)
        .map(([name, value]) => `${SCOPE} .fg-${name} { color: ${value} !important; }`)
        .join('\n');
    const ribbed = RIBBED.map(
        name =>
            `${SCOPE} .ribbed-${name} {\n` +
            `    background-color: ${ribbedColor(name)} !important;\n` +
            `    background-image: var(--metro-ribbed);\n` +
            `    background-size: 40px 40px;\n}`,
    ).join('\n');

    return (
        `${head}\n${SCOPE} {\n    --metro-ribbed: ${RIBBED_GRADIENT};\n}\n\n` +
        `/* ${Object.keys(COLORS).length} background colours */\n${bg}\n\n` +
        `/* ${Object.keys(COLORS).length} foreground colours */\n${fg}\n\n` +
        `/* ${RIBBED.length} ribbed surfaces */\n${ribbed}\n`
    );
}

/** class name -> colour value, read out of the original stylesheet. */
function readOriginal() {
    const css = readFileSync(ORIGINAL, 'utf8');
    const found = new Map();
    for (const [, selector, body] of css.matchAll(/([^{}]+)\{([^{}]*)\}/g)) {
        const match = selector.trim().match(/^\.metro \.((?:bg|fg|ribbed)-[A-Za-z-]+?)(:[a-z]+)?$/);
        if (!match) {
            continue;
        }
        const property = match[1].startsWith('fg-') ? /(?:^|[;\s])color:\s*([^;!]+)/ : /background-color:\s*([^;!]+)/;
        const value = body.match(property);
        if (value) {
            found.set(match[1], value[1].trim());
        }
    }
    return found;
}

function verify() {
    const original = readOriginal();
    const generated = new Map();
    for (const [name, value] of Object.entries(COLORS)) {
        generated.set(`bg-${name}`, value);
        generated.set(`fg-${name}`, value);
    }
    RIBBED.forEach(name => generated.set(`ribbed-${name}`, ribbedColor(name)));

    const same = (a, b) => a.toLowerCase() === b.toLowerCase();
    const mismatched = [...generated].filter(([n, v]) => original.has(n) && !same(original.get(n), v));
    const invented = [...generated.keys()].filter(n => !original.has(n));
    const dropped = [...original.keys()].filter(n => !generated.has(n));

    // Every dropped class must be a state variant that repeats its base value - otherwise we lose a colour.
    const states = Object.keys(STATES).join('|');
    const unexplained = dropped.filter(name => {
        const state = name.match(new RegExp(`^(bg|fg)-(${states})-(.+)$`));
        return !state || !same(original.get(name), original.get(`${state[1]}-${state[3]}`) ?? '');
    });

    console.log(`original colour classes : ${original.size}`);
    console.log(`generated               : ${generated.size}`);
    console.log(`value mismatches        : ${mismatched.length ? mismatched.map(([n, v]) => `${n} ${original.get(n)} != ${v}`).join(', ') : 'none'}`);
    console.log(`not in the original     : ${invented.join(' ') || 'none'}`);
    console.log(`dropped state variants  : ${dropped.length} (all redundant: ${unexplained.length === 0})`);
    if (unexplained.length) {
        console.log(`  carrying an own value : ${unexplained.join(' ')}`);
    }

    const ok = !mismatched.length && !invented.length && !unexplained.length;
    console.log(ok ? '\nOK - the generated palette covers the original without changing a value.' : '\nFAILED');
    return ok;
}

if (process.argv.includes('--verify')) {
    process.exit(verify() ? 0 : 1);
} else {
    const css = buildPaletteCss();
    writeFileSync(TARGET, css);
    console.log(`src/styles/metro-palette.css: ${(css.length / 1024).toFixed(1)} KB, ${css.split('\n').length} lines`);
}
